### ISSUE TITLE
[Feedback] disable analytics on local build

### ISSUE THREAD

**Issue by LordGhostX** [acid-info/logos-docusaurus-plugins#105]
By default, the Fathom analytics plugin remains enabled and captures information on local and production builds. Is it possible to configure it only to capture data during production?

![Screenshot_20230725-200128](https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/d23e36c5-3233-40ac-959f-dfa830ac07dd)

**Comment by jinhojang6** [comment]
@LordGhostX Thanks for the report. The team will discuss it and get back to you when we get to start developing this feature.

**Comment by jinhojang6** [comment]
@LordGhostX I will take this issue. Work in progress

**Comment by jinhojang6** [comment]
PR: https://github.com/acid-info/logos-docusaurus-plugins/pulls
