### ISSUE TITLE
Nomos: Commenting on Blog 

### ISSUE THREAD

**Issue by DeBelg** [acid-info/logos-docusaurus-plugins#107]
Request from Nomos to be able to allow people to comment on each article within their blog site. 

The primary goal would be to allow externals to share feedback on work in progress. In Alvaro's words:

"Not sure what formats we had in mind. Blog posts like Codex seem alright to me, although things like ethresear.ch are more prone to conversation. I think it's fine either way, as long as commenting is possible"

**Comment by amirhouieh** [comment]
@DeBelg ethersear.ch is a Discourse forum for which we also have similar space https://forum.logos.co/ and in case Nomos needs to have such a space then its different than enabling commenting on blog.

**Comment by amirhouieh** [comment]
Closing this issue because it actually needs to go through different channel. 
@DeBelg please follow up on this with Santiago.
