### ISSUE TITLE
Give a min-height to content on doc pages

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-docusaurus-plugins#33]
We need to assign a min height to each content container on documentation pages. Atm, if content is not long enough, you see the footer which is not nice. here is an example.
https://dev.logos.co/

**Comment by jinhojang6** [comment]
@amirhouieh @nireims 
Can you let me know how much min-height is needed? (e.g., 100vh, 800px)

**Comment by jinhojang6** [comment]
Under discussion with Veronika

**Comment by jinhojang6** [comment]
After discussion with Veronika:

The footer will be shown as soon as we scroll down as below

https://github.com/acid-info/logos-docusaurus-plugins/assets/41753422/b996fcd8-47dc-4d3f-8537-5e342d988436
