### ISSUE TITLE
[Feedback Sidebar Dropdown]

### ISSUE THREAD

**Issue by LordGhostX** [acid-info/logos-docusaurus-plugins#64]
An issue occurs with the styling of sidebar items with both a dropdown and a linked page. I'll show a comparison with the previous theme:

New theme: <https://dev-docs.waku.org/overview/concepts/peer-discovery>
Old theme: <https://docs.waku.org/overview/concepts/peer-discovery>

### 1. The page is not highlighted

The "Protocols" page is opened here, and there's a highlighting:

<img width="264" alt="Screenshot 2023-06-15 at 04 40 35" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/f1812b8f-ce53-4fc3-9943-cee74f595b92">
<img width="291" alt="Screenshot 2023-06-15 at 04 48 06" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/b378cbc3-256f-42e6-8089-2f553dc374ee">

The "Peer Discovery" page is opened, but there is no highlighting:

<img width="300" alt="Screenshot 2023-06-15 at 04 41 18" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/06e8b2e3-ef44-4488-8ed8-5f3479f40886">
<img width="288" alt="Screenshot 2023-06-15 at 04 48 42" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/28ee9760-6b7f-4e52-9e61-3b6d87c7a50f">

### 2. Dropdowns with pages aren't collapsing

<img width="300" alt="Screenshot 2023-06-15 at 04 41 18" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/06e8b2e3-ef44-4488-8ed8-5f3479f40886">
<img width="292" alt="Screenshot 2023-06-15 at 04 52 26" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/b6418caf-cff5-40ed-812f-635b158f81c6">

Try collapsing the dropdown of the "Peer Discovery" page using the arrow **after opening it once**.

### 3. Can we make the sidebar bigger?

There is a lot of space between the sidebar and the page. Can we increase the width of the sidebar so items are not cluttered?

<img width="745" alt="Screenshot 2023-06-15 at 05 13 57" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/343ebc0f-cedb-4d81-b441-c695f003a435">

**Comment by jinhojang6** [comment]
Thanks for reporting. the bullet point 1 and 3 are design issues so I cannot take action yet. But let me fix the bug no. 2, `Dropdowns with pages aren't collapsing`

**Comment by amirhouieh** [comment]
@ihor-hrtsk @nireims could you look into number 3 mentioned by Frank! If you can make a sketch that how it would look like, would be great.

**Comment by jinhojang6** [comment]
PR for No 1 & 2 : https://github.com/acid-info/logos-docusaurus-plugins/pull/68

**Comment by amirhouieh** [comment]
I feel this can resolve number 3 or make it easier. 
https://github.com/waku-org/waku.org/issues/44

**Comment by amirhouieh** [comment]
- [ x] 1.The page is not highlighted
- [ x] 2.Dropdowns with pages aren't collapsing
- [ ]  3. Can we make the sidebar bigger?

**Comment by nireims** [comment]
@amirhouieh seems like you missed it in discord
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/4f3f2ec6-bcfb-4205-aa1a-73f7537f7854)
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/887728d2-331d-4fd9-af5a-e7c9c26c4418)

**Comment by amirhouieh** [comment]
> @amirhouieh seems like you missed it in discord ![image](https://user-images.githubusercontent.com/115178918/246390483-4f3f2ec6-bcfb-4205-aa1a-73f7537f7854.png) ![image](https://user-images.githubusercontent.com/115178918/246390557-887728d2-331d-4fd9-af5a-e7c9c26c4418.png)

Ah, I do not remocing space between sidebar and main content worked.  Lets follow up on this on Discord.

**Comment by jinhojang6** [comment]
Closing the issue as we are not making the sidebar bigger at the moment.
