### ISSUE TITLE
Blog theme design enhancements

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-docusaurus-plugins#69]
@nireims it would be nice to enhance the design for blog index page and blog post/articles as follow 

- [x] Create a banner/hero section for `/blog` could be as simple as a headline (for example in case of vac it would be "Rlog - Vac Research Log" ) and ten a subtitle or description (for vac e.g; "Vac builds public good protocols for the decentralized web.") 
- [x] Design a article header to distinguish it from the rest of content. This can be aligned with LPE but not necessary. This part should content title, subtitle if any, date and authors  

example (not in terms of aesthetic) -> https://www.cloudquery.io/blog 

CC @jinhojang6 & @jeangovil

**Comment by nireims** [comment]
@amirhouieh how should the article header be different from this one? it has all the info you mentioned except for the subtitle
![1](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/3e794155-bac6-482c-a092-a76dae0b2efb)

**Comment by nireims** [comment]
@amirhouieh what do you think about making the hero section for `blog` the same as for `archive`
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/8413ea26-756a-4a15-8d92-b730e8c0f4a7)

**Comment by amirhouieh** [comment]
> @amirhouieh what do you think about making the hero section for `blog` the same as for `archive`? ![image](https://user-images.githubusercontent.com/115178918/246391141-8413ea26-756a-4a15-8d92-b730e8c0f4a7.png)

hmm not sure how it would work with blog posts cards. how do you envision it?

**Comment by nireims** [comment]
> > @amirhouieh how should the article header be different from this one? it has all the info you mentioned except for the subtitle ![1](https://user-images.githubusercontent.com/115178918/246387795-3e794155-bac6-482c-a092-a76dae0b2efb.png)
> 
> Yes slightly more noticeable, blog posts should be different that normal doc pages. and why this doc pages shows authors name and the date? for these pages we only show the date and we only show it in the article footer. I believe this sketch is old one, right?

OK.
It shows authors' names and date because you asked me to add them and I didn't know that it's outdated. I can remove it from designs if you want.

**Comment by amirhouieh** [comment]
> > > @amirhouieh how should the article header be different from this one? it has all the info you mentioned except for the subtitle ![1](https://user-images.githubusercontent.com/115178918/246387795-3e794155-bac6-482c-a092-a76dae0b2efb.png)
> > 
> > 
> > Yes slightly more noticeable, blog posts should be different that normal doc pages. and why this doc pages shows authors name and the date? for these pages we only show the date and we only show it in the article footer. I believe this sketch is old one, right?
> 
> OK. It shows authors' names and date because you asked me to add them and I didn't know that it's outdated. I can remove it from designs if you want.

hmm what about slightly large typography for headline, and a bit more spacing?

**Comment by nireims** [comment]
> > @amirhouieh what do you think about making the hero section for `blog` the same as for `archive`? ![image](https://user-images.githubusercontent.com/115178918/246391141-8413ea26-756a-4a15-8d92-b730e8c0f4a7.png)
> 
> hmm not sure how it would work with blog posts cards. how do you envision it?

I was thinking something like this
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/c7d30d01-7369-43ca-8c35-afeb44e6a05f)
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/0456e888-9606-433e-8cca-fe54ed553d40)
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/35b06549-0642-4226-91de-ac2e2fc99f60)
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/91dd7473-bd62-41e0-b8ee-61d567df62c6)

**Comment by nireims** [comment]
> > > > @amirhouieh how should the article header be different from this one? it has all the info you mentioned except for the subtitle ![1](https://user-images.githubusercontent.com/115178918/246387795-3e794155-bac6-482c-a092-a76dae0b2efb.png)
> > > 
> > > 
> > > Yes slightly more noticeable, blog posts should be different that normal doc pages. and why this doc pages shows authors name and the date? for these pages we only show the date and we only show it in the article footer. I believe this sketch is old one, right?
> > 
> > 
> > OK. It shows authors' names and date because you asked me to add them and I didn't know that it's outdated. I can remove it from designs if you want.
> 
> hmm what about slightly large typography for headline, and a bit more spacing?

What do you think?
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/df9072a8-f87e-429b-b28a-ded1149ad97e)
![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/8040780f-e1a2-46c4-b8f4-36d256bb6d44)

**Comment by nireims** [comment]
@amirhouieh here's some new options
![blog](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/c780c143-66cd-4b93-b064-b57e1ca6763a)
![blog-1](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/97a28a34-30a0-4568-9860-4fda897276cf)
![blog-2](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/659cf30f-3690-4e14-be16-51b0ab9dc8d6)
![blog-3](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/a3de70c0-34a7-4c48-b9b2-27be7a96ab7a)

**Comment by nireims** [comment]
> @amirhouieh here's some new options ![blog](https://user-images.githubusercontent.com/115178918/246877475-c780c143-66cd-4b93-b064-b57e1ca6763a.png) ![blog-1](https://user-images.githubusercontent.com/115178918/246877465-97a28a34-30a0-4568-9860-4fda897276cf.png) ![blog-2](https://user-images.githubusercontent.com/115178918/246877470-659cf30f-3690-4e14-be16-51b0ab9dc8d6.png) ![blog-3](https://user-images.githubusercontent.com/115178918/246877473-a3de70c0-34a7-4c48-b9b2-27be7a96ab7a.png)

![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/32a3b1ed-a90b-49b1-aea9-42d548804f57)

**Comment by amirhouieh** [comment]
> @amirhouieh here's some new options ![blog](https://user-images.githubusercontent.com/115178918/246877475-c780c143-66cd-4b93-b064-b57e1ca6763a.png) ![blog-1](https://user-images.githubusercontent.com/115178918/246877465-97a28a34-30a0-4568-9860-4fda897276cf.png) ![blog-2](https://user-images.githubusercontent.com/115178918/246877470-659cf30f-3690-4e14-be16-51b0ab9dc8d6.png)

thanks @nireims for sharing. I suggest to go with 3x column. Also given the fact that the majority of these posts wont have an image, I suggest to remove the image for now. Because the layout you propsoed (Pintrest like) is more work than simple layout like what for example we have in LPE (wehere each row has a fixed height). So in order to resolve this and move forward i suggest to remove the images for this stage. what do you think?

**Comment by jinhojang6** [comment]
Pull request: https://github.com/acid-info/logos-docusaurus-plugins/pull/71
