### ISSUE TITLE
Enhance the content of README

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-docusaurus-plugins#81]
We need a more elaborative version of README which explains different options and configs either the ones from Docu or the one built into Logos Plugin.

**Comment by amirhouieh** [comment]
@jinhojang6 did you also look into this and if there is an update?

**Comment by jinhojang6** [comment]
@amirhouieh I've updated the README of all the BUs and LPE based on the Notion task. Let me update the plugin also by this week

**Comment by amirhouieh** [comment]
We are going to move the documentation to each package. 
- [ ] OG image 
- [ ] Search 
- [ ] Logos presets 
- [ ] Fathom
- [ ] Logos-Theme
