### ISSUE TITLE
Support for fathom JS

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-docusaurus-plugins#86]
Some BUs require to inject fathom JS snipped to their client. It seems that we might nether to add some code or develop a plugin for it. [Here is a relavant discussion](https://github.com/facebook/docusaurus/issues/3399#issuecomment-1067890789).

atm, only Waku has asked but we need to make it scalable so parameters can be customized. Here is the sample script received from @serhanwbahar. 

```
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
(function(f, a, t, h, o, m){
    a[h]=a[h]||function(){
        (a[h].q=a[h].q||[]).push(arguments)
    };
    o=f.createElement('script'),
    m=f.getElementsByTagName('script')[0];
    o.async=1; o.src=t; o.id='fathom-script';
    m.parentNode.insertBefore(o,m)
})(document, window, '//fathom.status.im/tracker.js', 'fathom');
fathom('set', 'siteId', 'FUTMI');
fathom('trackPageview');
</script>
<!-- / Fathom -->
```

**Comment by fryorcraken** [comment]
For docs.waku.org, can we just include the snippet somewhere in the docs.waku.org repo for now, and remove it once plugin is in place? Cc @LordGhostX

**Comment by jinhojang6** [comment]
I think we can, if it is urgent. What do you think @jeangovil ?

**Comment by jinhojang6** [comment]
@amirhouieh I am new to the client module and integrating a plugin so need some initial time to understand this. Will submit a pull request today.

**Comment by jinhojang6** [comment]
Pull Request at https://github.com/acid-info/logos-docusaurus-plugins/pull/87

**Comment by jinhojang6** [comment]
Pull request to implement fathom for docs.waku.org : https://github.com/waku-org/docs.waku.org/pull/76

**Comment by jinhojang6** [comment]
Solved all the issues with the infra team
