### ISSUE TITLE
[Feature] Custom 404 Page

### ISSUE THREAD

**Issue by LordGhostX** [acid-info/logos-docusaurus-plugins#98]
Are there plans to design/implement a custom 404 page for the theme? Here's the current:

<img width="1440" alt="Screenshot 2023-07-11 at 18 31 54" src="https://github.com/acid-info/logos-docusaurus-plugins/assets/47832826/54a86870-32e6-44ec-af7c-618f8c6b1993">

**Comment by nireims** [comment]
@amirhouieh what do you think?

![image](https://github.com/acid-info/logos-docusaurus-plugins/assets/115178918/d706cad9-4033-452e-905e-0ab9cb88423f)
